# Generated by Django 4.1.1 on 2022-10-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dept",
            name="dept_url_shorthand",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dept",
            name="dept_name",
            field=models.CharField(max_length=50),
        ),
    ]
