# Generated by Django 4.1.1 on 2022-10-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0002_search"),
        ("louslist", "0003_subject"),
    ]

    operations = []
