# Generated by Django 4.1.1 on 2022-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0004_merge_0002_search_0003_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "course_num",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("course", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("instructor", models.CharField(max_length=50)),
                ("meeting_days", models.CharField(max_length=10)),
                ("meeting_time", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
    ]
