# Generated by Django 4.1.1 on 2022-11-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0005_coursemodel"),
        ("louslist", "0005_subject_rating"),
    ]

    operations = []
