# Generated by Django 4.1.1 on 2022-11-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0005_friendship_friendrequest"),
        ("louslist", "0006_merge_0005_coursemodel_0005_subject_rating"),
    ]

    operations = []
