# Generated by Django 4.1.1 on 2022-11-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0009_averagerating_rating_delete_friend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averagerating",
            name="course_num",
            field=models.CharField(max_length=6),
        ),
    ]
