# Generated by Django 4.1.1 on 2022-11-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0011_rename_averagerating_courserating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="rating",
        ),
    ]
