# Generated by Django 4.1.1 on 2022-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0012_remove_subject_rating"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("user", "course"), name="user_rates_once_per_course"
            ),
        ),
    ]
