# Generated by Django 4.1.1 on 2022-12-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0015_alter_rating_rating_schedule_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="course_num",
            field=models.IntegerField(default=789),
            preserve_default=False,
        ),
    ]
