# Generated by Django 4.1.1 on 2022-12-06 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("louslist", "0017_commenttext_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commenttext",
            name="name",
        ),
        migrations.AlterField(
            model_name="commenttext",
            name="publish_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="commenttext",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="louslist.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="commenttext",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="commenttext",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
