# Generated by Django 4.1.1 on 2022-12-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0018_remove_commenttext_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commenttext",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
