# Generated by Django 4.1.1 on 2022-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0002_alter_event_course_num"),
        ("louslist", "0019_commenttext_name"),
    ]

    operations = []
